services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchises_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      R2DBC_URL: r2dbc:mysql://example-mysql-db.ckjm0u2ckv05.us-east-1.rds.amazonaws.com:3306/accenture_db
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: terraform*
      SERVER_PORT: 8080
   

